<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:tns="http://org.ow2.petals/demo/travelagency/agency/Artifacts" xmlns:vprop="http://docs.oasis-open.org/wsbpel/2.0/varprop" xmlns:wsdl="http://org.ow2.petals/demo/travelagency/airline/" xmlns:wsdl1="http://org.ow2.petals/demo/travelagency/hotel/" xmlns:wsdl2="http://org.ow2.petals/demo/travelagency/agency/" xmlns:car="http://org.ow2.petals/demo/travelagency/car/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="processArtifacts" targetNamespace="http://org.ow2.petals/demo/travelagency/agency/Artifacts">

    <import location="car.wsdl" namespace="http://org.ow2.petals/demo/travelagency/car/"/>
</definitions>
